--- #YAML:1.0
name:                Prompt-ReadKey
version:             0.01
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Moose:                         0.33
    Scalar::Util:                  0
    Term::ReadKey:                 0
    Test::use::ok:                 0
    Text::Table:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
