---
abstract: 'Darcs style single readkey option prompt.'
author:
  - 'Yuval Kogman <nothingmuch@woobling.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::Fatal: 0
  Test::use::ok: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Prompt-ReadKey
no_index:
  directory:
    - inc
    - t
requires:
  List::Util: 0
  Moose: 0.33
  Scalar::Util: 0
  Set::Object: 0
  Term::ReadKey: 0
  Text::Sprintf::Named: 0
  Text::Table: 0
resources:
  homepage: https://github.com/sartak/prompt-readkey/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/sartak/prompt-readkey.git
version: 0.04
